export enum ErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_INACTIVE = 'USER_INACTIVE',
  SESSION_TENANT_MISMATCH = 'SESSION_TENANT_MISMATCH',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  CANNOT_DEMOTE_LAST_OWNER = 'CANNOT_DEMOTE_LAST_OWNER',
  SUPERADMIN_CANNOT_BELONG_TO_TENANT = 'SUPERADMIN_CANNOT_BELONG_TO_TENANT',

  VALIDATION_FAILED = 'VALIDATION_FAILED',
  DUPLICATE_RECORD = 'DUPLICATE_RECORD',
  RELATED_RECORD_NOT_FOUND = 'RELATED_RECORD_NOT_FOUND',
  REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
  CONSTRAINT_VIOLATION = 'CONSTRAINT_VIOLATION',
  TENANT_CONTEXT_MISSING = 'TENANT_CONTEXT_MISSING',
  SEED_DISABLED = 'SEED_DISABLED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
